"""
Django settings for agence_transport project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j1z874z8*q3490-obm%)go7c5=orszv&j1shzgrnto9tnidi4-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.humanize',
    
    # Third-party apps
    'crispy_forms',
    'crispy_bootstrap5',
    'allauth',
    'allauth.account',
    # 'allauth.socialaccount',  # Désactivé temporairement
    'debug_toolbar',
    
    # Local apps
    'reservations.apps.ReservationsConfig',
]

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

# Configuration pour django-debug-toolbar
INTERNAL_IPS = [
    '127.0.0.1',
]

ROOT_URLCONF = 'agence_transport.urls'

# Chemin vers le répertoire des templates de l'application reservations
RESERVATIONS_TEMPLATES = os.path.join(BASE_DIR, 'reservations', 'templates')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            RESERVATIONS_TEMPLATES,
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                'currency_filters': 'reservations.templatetags.currency_filters',
                'custom_filters': 'reservations.templatetags.custom_filters',
            },
        },
    },
]

WSGI_APPLICATION = 'agence_transport.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Configuration d'Allauth
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = 'none'  # 'mandatory' pour forcer la vérification d'email

# Désactive les comptes sociaux
SOCIALACCOUNT_ENABLED = False

SITE_ID = 1

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Stripe
STRIPE_PUBLIC_KEY = 'votre_cle_publique_stripe'
STRIPE_SECRET_KEY = 'votre_cle_secrete_stripe'
STRIPE_WEBHOOK_SECRET = 'votre_webhook_secret_stripe'

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_TIMEOUT = 30  # Timeout en secondes
EMAIL_SSL_KEYFILE = None
EMAIL_SSL_CERTFILE = None

# Configuration pour Gmail (à remplacer par vos identifiants)
EMAIL_HOST_USER = 'votre_email@gmail.com'  # Votre adresse Gmail
EMAIL_HOST_PASSWORD = 'votre_mot_de_passe_application'  # Mot de passe d'application Gmail

# En mode DEBUG, on affiche les emails dans la console
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Configuration des emails
DEFAULT_FROM_EMAIL = 'votre_email@gmail.com'  # Doit correspondre à EMAIL_HOST_USER
DEFAULT_TO_EMAIL = 'votre_email@gmail.com'  # Email par défaut pour les envois
SERVER_EMAIL = 'votre_email@gmail.com'  # Email pour les erreurs

# Configuration pour les erreurs d'email
ADMINS = [
    ('Admin', 'votre_email@gmail.com'),
]
MANAGERS = ADMINS

# Configuration du site
SITE_URL = 'http://127.0.0.1:8000'  # URL de base du site
CONTACT_PHONE = '+33 1 23 45 67 89'  # Numéro de contact de l'agence

# Configuration des messages
MESSAGE_TAGS = {
    10: 'debug',
    20: 'info',
    25: 'success',
    30: 'warning',
    40: 'danger',
}

# Configuration des sessions
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # La session expire quand le navigateur est fermé
SESSION_COOKIE_AGE = 1800  # Durée de la session en secondes (30 minutes)
SESSION_SAVE_EVERY_REQUEST = True  # Rafraîchir la session à chaque requête

# Login/Logout URLs
LOGIN_REDIRECT_URL = 'reservations:home'  # Utilisation du namespace 'reservations'
LOGOUT_REDIRECT_URL = 'reservations:home'  # Redirige vers la page d'accueil après déconnexion
ACCOUNT_LOGOUT_ON_GET = True
