# Generated by Django 5.2.8 on 2025-11-29 11:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depart', models.DateTimeField()),
                ('date_arrivee', models.DateTimeField()),
                ('prix_base', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('places_disponibles', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['date_depart'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('PEND', 'En attente'), ('COMP', 'Complété'), ('FAIL', 'Échoué'), ('REFU', 'Remboursé')], default='PEND', max_length=4)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('points_fidelite', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('motif', models.TextField()),
                ('traite', models.BooleanField(default=False)),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='remboursement', to='reservations.paiement')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('CONF', 'Confirmée'), ('ANNU', 'Annulée'), ('UTIL', 'Utilisée'), ('REMB', 'Remboursée')], default='CONF', max_length=4)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(max_length=10, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.client')),
                ('horaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='reservations.horaire')),
            ],
            options={
                'ordering': ['-date_reservation'],
            },
        ),
        migrations.AddField(
            model_name='paiement',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='reservations.reservation'),
        ),
        migrations.CreateModel(
            name='Billet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_billet', models.CharField(choices=[('STD', 'Standard'), ('PRE', 'Première Classe'), ('BUS', 'Business')], default='STD', max_length=3)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('siege', models.CharField(max_length=10)),
                ('code_qr', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billets', to='reservations.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='TicketBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
                ('utilise', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_bonus', to='reservations.client')),
            ],
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree', models.DurationField()),
                ('distance', models.PositiveIntegerField(help_text='Distance en kilomètres')),
                ('actif', models.BooleanField(default=True)),
                ('arrivee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivees', to='reservations.gare')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departs', to='reservations.gare')),
            ],
            options={
                'unique_together': {('depart', 'arrivee')},
            },
        ),
        migrations.AddField(
            model_name='horaire',
            name='trajet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='reservations.trajet'),
        ),
        migrations.AddField(
            model_name='gare',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gares', to='reservations.ville'),
        ),
        migrations.AlterUniqueTogether(
            name='gare',
            unique_together={('nom', 'ville')},
        ),
    ]
