# Generated by Django 5.2.8 on 2025-12-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='numero_telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='operateur',
            field=models.CharField(blank=True, choices=[('lumicash', 'Lumicash'), ('ecocash', 'Ecocash'), ('ihela', 'Ihela'), ('paypal', 'PayPal'), ('carte', 'Carte bancaire')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='reference_paiement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('PEND', 'En attente'), ('PAID', 'Payé'), ('FAIL', 'Échoué'), ('REFD', 'Remboursé')], default='PEND', max_length=4),
        ),
    ]
