# Generated by Django 5.2.8 on 2025-12-06 15:34

from django.db import migrations, models
import django.utils.timezone


def set_default_values(apps, schema_editor):
    # Récupérer le modèle Horaire
    Horaire = apps.get_model('reservations', 'Horaire')
    
    # Mettre à jour les enregistrements existants avec des valeurs par défaut
    for horaire in Horaire.objects.all():
        # Utiliser les valeurs existantes ou des valeurs par défaut
        horaire.prix_standard = horaire.prix_base if hasattr(horaire, 'prix_base') else 0
        horaire.prix_business = 0  # Valeur par défaut
        horaire.prix_premiere = 0  # Valeur par défaut
        
        # Répartir les places disponibles
        total_places = horaire.places_disponibles if hasattr(horaire, 'places_disponibles') else 0
        horaire.places_standard = total_places  # Toutes les places en standard par défaut
        horaire.places_business = 0  # Aucune place en business par défaut
        horaire.places_premiere = 0  # Aucune place en première par défaut
        
        horaire.save()


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_paiement_numero_telephone_paiement_operateur_and_more'),
    ]

    operations = [
        # Ajout des nouveaux champs
        migrations.AddField(
            model_name='horaire',
            name='prix_standard',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix Standard (BIF)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horaire',
            name='prix_business',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix Business (BIF)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horaire',
            name='prix_premiere',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix Première Classe (BIF)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horaire',
            name='places_standard',
            field=models.PositiveIntegerField(default=0, verbose_name='Places Standard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horaire',
            name='places_business',
            field=models.PositiveIntegerField(default=0, verbose_name='Places Business'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horaire',
            name='places_premiere',
            field=models.PositiveIntegerField(default=0, verbose_name='Places Première Classe'),
            preserve_default=False,
        ),
        
        # Exécuter la fonction pour définir les valeurs par défaut
        migrations.RunPython(set_default_values, migrations.RunPython.noop),
        
        # Supprimer les anciens champs après la migration des données
        migrations.RemoveField(
            model_name='horaire',
            name='prix_base',
        ),
        migrations.RemoveField(
            model_name='horaire',
            name='places_disponibles',
        ),
    ]
