# Generated by Django 5.2.8 on 2025-12-10 17:18

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_update_horaire_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horaire',
            options={'ordering': ['date_depart'], 'verbose_name': 'Horaire', 'verbose_name_plural': 'Horaires'},
        ),
        migrations.AddField(
            model_name='client',
            name='places_reservees',
            field=models.PositiveIntegerField(default=0, help_text='Nombre total de places réservées'),
        ),
        migrations.AddField(
            model_name='ticketbonus',
            name='nombre_places',
            field=models.PositiveIntegerField(default=1, help_text='Nombre de places offertes par ce ticket'),
        ),
        migrations.AlterField(
            model_name='horaire',
            name='prix_business',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix Business (BIF)'),
        ),
        migrations.AlterField(
            model_name='horaire',
            name='prix_premiere',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix Première Classe (BIF)'),
        ),
        migrations.AlterField(
            model_name='horaire',
            name='prix_standard',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix Standard (BIF)'),
        ),
        migrations.AlterField(
            model_name='ticketbonus',
            name='code',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='ticketbonus',
            name='date_expiration',
            field=models.DateTimeField(help_text="Date d'expiration du ticket (30 jours après création)"),
        ),
        migrations.AlterField(
            model_name='ticketbonus',
            name='montant',
            field=models.DecimalField(decimal_places=2, help_text='Montant du bon de réduction', max_digits=10),
        ),
    ]
